language: go

os: linux

go: # use travis ci resource effectively, keep always latest 2 versions and tip :) 
  - 1.15.x
  - 1.14.x
  - tip

install:
  - go get -v -t ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  allow_failures:
    - go: tip
