language: go

sudo: false

# branches:
#   only:
#     - master
#     - integration

language: go

go:
  - 1.8
  - 1.9
  - tip

env:
  - DEP_VERSION=0.4.1

before_install:
  - curl -fsSL -o $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v$DEP_VERSION/dep-linux-amd64
  -	chmod +x $GOPATH/bin/dep
  - dep ensure

script:
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
