language: go

sudo: false

# branches:
#   only:
#     - master
#     - integration

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - go get -v -t ./...

script:
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
